/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ./public/TimeMachine.glb -o src/models/TimeMachine 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function TimeMachine(props) {
  const { nodes, materials } = useGLTF('/TimeMachine.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_0.geometry} material={materials.Material_0} position={[-0.058, 0.219, -0.17]} />
    </group>
  )
}

useGLTF.preload('/TimeMachine.glb')
