/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ./public/Tree3.glb -o src/models/Tree3.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { useBox } from '@react-three/cannon';

export function Tree3Model(props) {
  const { nodes, materials } = useGLTF('/Tree3.glb')

  const [ref] = useBox(() => ({
    mass: 0, // Static object
    type:'Static',
    position: props.position, // Pass position from props
    args: [1, 5, 1], // Size of the box collider (adjust as needed)
  }));

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.sub02.geometry} material={materials['Tree.Birch.Leaf.Summer.Mat']} />
      <mesh geometry={nodes.sub02_1.geometry} material={materials['Tree.Birch.Bark.Mat']} />
    </group>
  )
}

useGLTF.preload('/Tree3.glb')
