/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ./public/Tree2.glb -o src/models/Tree2.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { useBox } from '@react-three/cannon';

export function Tree2Model(props) {
  const { nodes, materials } = useGLTF('/Tree2.glb')

  const [ref] = useBox(() => ({
    mass: 0, // Static object
    type:'Static',
    position: props.position, // Pass position from props
    args: [1, 5, 1], // Size of the box collider (adjust as needed)
  }));
  
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.tree.geometry} material={materials['Material.002']}>
        <mesh geometry={nodes.leaves.geometry} material={materials['Material.001']} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/Tree2.glb')
