/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ./public/CleanedCity1.glb -o ./src/ModernCity/Models/City.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { RigidBody } from '@react-three/rapier'

export function CityModel(props) {
  const { nodes, materials } = useGLTF('/CleanedCity1.glb')
  return (
    <group {...props} dispose={null}>
      <RigidBody type="fixed"> 
      <mesh geometry={nodes.BD_ConcreteBlock1_RoadsGround_0.geometry} material={materials.RoadsGround} scale={0.01} />
      </RigidBody>
      <mesh geometry={nodes.polySurface98_FillerBuildings1_0.geometry} material={materials.FillerBuildings1} position={[-173.616, 2.955, -88.102]} rotation={[0, -Math.PI / 2, 0]} scale={[0, 0.001, 0.004]} />
      <mesh geometry={nodes.polySurface131_FillerBuildings1GLOW_0.geometry} material={materials.FillerBuildings1GLOW} position={[-168.518, 11.603, -84.394]} scale={[0.027, 0.012, 0.007]} />
      <mesh geometry={nodes.LM_Basketball11_Basketball_0.geometry} material={materials.Basketball} position={[-71.5, 0, -466.5]} rotation={[0, Math.PI / 2, 0]} scale={0.01} />
      <mesh geometry={nodes.LM_Clinic2_Clinic_0.geometry} material={materials.Clinic} scale={0.01} />
      <mesh geometry={nodes.LM_Laundrette_pasted__pCube65_Laundrymat_0.geometry} material={materials.Laundrymat} scale={0.01} />
      <mesh geometry={nodes.polySurface6_Paramount1GLOW_0.geometry} material={materials.Paramount1GLOW} position={[-223.295, 0.048, -86.61]} scale={0.01} />
      <mesh geometry={nodes.pPlane329_Paramount_0.geometry} material={materials.Paramount} position={[-211.921, 13.632, -82.141]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.014, 0.01, 0.01]} />
      <mesh geometry={nodes.pasted__polySurface805_Pawnshop_0.geometry} material={materials.Pawnshop} position={[-251, 14, -90.5]} scale={0.01} />
      <mesh geometry={nodes.pasted__pCube88_Pawnshop1GLOW_0.geometry} material={materials.Pawnshop1GLOW} position={[-251.026, 8.959, -81.477]} scale={[0.004, 0.009, 0.03]} />
      <mesh geometry={nodes.LMProjects2_pasted__group65_pasted__pCube39_LMProjects1GLOW_0.geometry} material={materials.LMProjects1GLOW} scale={0.01} />
      <mesh geometry={nodes.LMProjects2_pasted__group65_pasted__pCube40_LMProjects_0.geometry} material={materials.LMProjects} scale={0.01} />
      <mesh geometry={nodes.polySurface259_CityProps_0001.geometry} material={materials.CityProps} position={[-150.5, 0, -79]} rotation={[0, -Math.PI / 2, 0]} scale={0.01} />
      <mesh geometry={nodes.polySurface791_CityProps1GLOW_0001.geometry} material={materials.CityProps1GLOW} position={[-150.5, 0, -79]} rotation={[0, -Math.PI / 2, 0]} scale={0.01} />
      <mesh geometry={nodes.polySurface739_GreenGlow_0.geometry} material={materials.PaletteMaterial001} position={[-150.5, 0, -79]} rotation={[0, -Math.PI / 2, 0]} scale={0.01} />
      <instancedMesh args={[nodes.pCube23_FillerBuildings1_0.geometry, materials.FillerBuildings1, 4]} instanceMatrix={nodes.pCube23_FillerBuildings1_0.instanceMatrix} />
      <instancedMesh args={[nodes.pCylinder7_FillerBuildings1_0.geometry, materials.FillerBuildings1, 4]} instanceMatrix={nodes.pCylinder7_FillerBuildings1_0.instanceMatrix} />
      <instancedMesh args={[nodes.polySurface97_FillerBuildings1_0.geometry, materials.FillerBuildings1, 2]} instanceMatrix={nodes.polySurface97_FillerBuildings1_0.instanceMatrix} />
      <instancedMesh args={[nodes.polySurface98_FillerBuildings1_0001.geometry, materials.FillerBuildings1, 3]} instanceMatrix={nodes.polySurface98_FillerBuildings1_0001.instanceMatrix} />
      <instancedMesh args={[nodes.pCube26_FillerBuildings1_0.geometry, materials.FillerBuildings1, 2]} instanceMatrix={nodes.pCube26_FillerBuildings1_0.instanceMatrix} />
      <instancedMesh args={[nodes.pCube29_FillerBuildings1_0.geometry, materials.FillerBuildings1, 2]} instanceMatrix={nodes.pCube29_FillerBuildings1_0.instanceMatrix} />
      <instancedMesh args={[nodes.pCube30_FillerBuildings1_0.geometry, materials.FillerBuildings1, 2]} instanceMatrix={nodes.pCube30_FillerBuildings1_0.instanceMatrix} />
      <instancedMesh args={[nodes.pCube31_FillerBuildings1_0.geometry, materials.FillerBuildings1, 2]} instanceMatrix={nodes.pCube31_FillerBuildings1_0.instanceMatrix} />
      <instancedMesh args={[nodes.pCube32_FillerBuildings1_0.geometry, materials.FillerBuildings1, 2]} instanceMatrix={nodes.pCube32_FillerBuildings1_0.instanceMatrix} />
      <instancedMesh args={[nodes.pCube33_FillerBuildings1_0.geometry, materials.FillerBuildings1, 2]} instanceMatrix={nodes.pCube33_FillerBuildings1_0.instanceMatrix} />
      <instancedMesh args={[nodes.pCylinder9_FillerBuildings1_0.geometry, materials.FillerBuildings1, 8]} instanceMatrix={nodes.pCylinder9_FillerBuildings1_0.instanceMatrix} />
      <instancedMesh args={[nodes.polySurface112_FillerBuildings1_0.geometry, materials.FillerBuildings1, 2]} instanceMatrix={nodes.polySurface112_FillerBuildings1_0.instanceMatrix} />
      <instancedMesh args={[nodes.polySurface113_FillerBuildings1_0.geometry, materials.FillerBuildings1, 2]} instanceMatrix={nodes.polySurface113_FillerBuildings1_0.instanceMatrix} />
      <instancedMesh args={[nodes.polySurface116_FillerBuildings1_0.geometry, materials.FillerBuildings1, 5]} instanceMatrix={nodes.polySurface116_FillerBuildings1_0.instanceMatrix} />
      <instancedMesh args={[nodes.polySurface118_FillerBuildings1_0.geometry, materials.FillerBuildings1, 3]} instanceMatrix={nodes.polySurface118_FillerBuildings1_0.instanceMatrix} />
      <instancedMesh args={[nodes.polySurface120_FillerBuildings1_0.geometry, materials.FillerBuildings1, 7]} instanceMatrix={nodes.polySurface120_FillerBuildings1_0.instanceMatrix} />
      <instancedMesh args={[nodes.polySurface124_FillerBuildings1_0.geometry, materials.FillerBuildings1, 2]} instanceMatrix={nodes.polySurface124_FillerBuildings1_0.instanceMatrix} />
      <instancedMesh args={[nodes.polySurface257_FillerBuildings1_0.geometry, materials.FillerBuildings1, 2]} instanceMatrix={nodes.polySurface257_FillerBuildings1_0.instanceMatrix} />
      <instancedMesh args={[nodes.pCube103_FillerBuildings1_0.geometry, materials.FillerBuildings1, 2]} instanceMatrix={nodes.pCube103_FillerBuildings1_0.instanceMatrix} />
      <instancedMesh args={[nodes.pCube34_FillerBuildings1_0.geometry, materials.FillerBuildings1, 2]} instanceMatrix={nodes.pCube34_FillerBuildings1_0.instanceMatrix} />
      <instancedMesh args={[nodes.polySurface137_FillerBuildings1_0.geometry, materials.FillerBuildings1, 6]} instanceMatrix={nodes.polySurface137_FillerBuildings1_0.instanceMatrix} />
      <instancedMesh args={[nodes.polySurface804_FillerBuildings1_0.geometry, materials.FillerBuildings1, 3]} instanceMatrix={nodes.polySurface804_FillerBuildings1_0.instanceMatrix} />
      <instancedMesh args={[nodes.polySurface814_FillerBuildings1_0.geometry, materials.FillerBuildings1, 2]} instanceMatrix={nodes.polySurface814_FillerBuildings1_0.instanceMatrix} />
      <instancedMesh args={[nodes.pCube17_FillerBuildings1_0.geometry, materials.FillerBuildings1, 3]} instanceMatrix={nodes.pCube17_FillerBuildings1_0.instanceMatrix} />
      <instancedMesh args={[nodes.polySurface129_FillerBuildings1_0.geometry, materials.FillerBuildings1, 3]} instanceMatrix={nodes.polySurface129_FillerBuildings1_0.instanceMatrix} />
      <instancedMesh args={[nodes.pasted__BD_Block88_Laundrymat_0.geometry, materials.Laundrymat, 4]} instanceMatrix={nodes.pasted__BD_Block88_Laundrymat_0.instanceMatrix} />
      <instancedMesh args={[nodes.pasted__pCube23_Laundrymat_0.geometry, materials.Laundrymat, 2]} instanceMatrix={nodes.pasted__pCube23_Laundrymat_0.instanceMatrix} />
      <instancedMesh args={[nodes.pasted__pCylinder7_Laundrymat_0.geometry, materials.Laundrymat, 2]} instanceMatrix={nodes.pasted__pCylinder7_Laundrymat_0.instanceMatrix} />
      <instancedMesh args={[nodes.pasted__pCube72_Laundrymat_0.geometry, materials.Laundrymat, 3]} instanceMatrix={nodes.pasted__pCube72_Laundrymat_0.instanceMatrix} />
      <instancedMesh args={[nodes.pasted__pCube69_Laundrymat_0001.geometry, materials.Laundrymat, 2]} instanceMatrix={nodes.pasted__pCube69_Laundrymat_0001.instanceMatrix} />
      <instancedMesh args={[nodes.pasted__pCube71_Laundrymat_0001.geometry, materials.Laundrymat, 2]} instanceMatrix={nodes.pasted__pCube71_Laundrymat_0001.instanceMatrix} />
      <instancedMesh args={[nodes.pCube4_Paramount_0.geometry, materials.Paramount, 2]} instanceMatrix={nodes.pCube4_Paramount_0.instanceMatrix} />
      <instancedMesh args={[nodes.pCube5_Paramount_0.geometry, materials.Paramount, 2]} instanceMatrix={nodes.pCube5_Paramount_0.instanceMatrix} />
      <instancedMesh args={[nodes.polySurface10_Paramount_0.geometry, materials.Paramount, 2]} instanceMatrix={nodes.polySurface10_Paramount_0.instanceMatrix} />
      <instancedMesh args={[nodes.polySurface11_Paramount_0.geometry, materials.Paramount, 2]} instanceMatrix={nodes.polySurface11_Paramount_0.instanceMatrix} />
      <instancedMesh args={[nodes.polySurface12_Paramount_0.geometry, materials.Paramount, 2]} instanceMatrix={nodes.polySurface12_Paramount_0.instanceMatrix} />
      <instancedMesh args={[nodes.polySurface4_Paramount_0.geometry, materials.Paramount, 2]} instanceMatrix={nodes.polySurface4_Paramount_0.instanceMatrix} />
      <instancedMesh args={[nodes.polySurface9_Paramount_0.geometry, materials.Paramount, 2]} instanceMatrix={nodes.polySurface9_Paramount_0.instanceMatrix} />
      <instancedMesh args={[nodes.polySurface3_Paramount1GLOW_0.geometry, materials.Paramount1GLOW, 2]} instanceMatrix={nodes.polySurface3_Paramount1GLOW_0.instanceMatrix} />
      <instancedMesh args={[nodes.polySurface5_Paramount1GLOW_0.geometry, materials.Paramount1GLOW, 2]} instanceMatrix={nodes.polySurface5_Paramount1GLOW_0.instanceMatrix} />
      <instancedMesh args={[nodes.polySurface7_Paramount1GLOW_0.geometry, materials.Paramount1GLOW, 2]} instanceMatrix={nodes.polySurface7_Paramount1GLOW_0.instanceMatrix} />
      <instancedMesh args={[nodes.pPlane332_Paramount1GLOW_0.geometry, materials.Paramount1GLOW, 2]} instanceMatrix={nodes.pPlane332_Paramount1GLOW_0.instanceMatrix} />
      <instancedMesh args={[nodes.pPlane57_Paramount1GLOW_0.geometry, materials.Paramount1GLOW, 3]} instanceMatrix={nodes.pPlane57_Paramount1GLOW_0.instanceMatrix} />
      <instancedMesh args={[nodes.pPlane58_Paramount1GLOW_0.geometry, materials.Paramount1GLOW, 3]} instanceMatrix={nodes.pPlane58_Paramount1GLOW_0.instanceMatrix} />
      <instancedMesh args={[nodes.pPlane338_Paramount_0.geometry, materials.Paramount, 9]} instanceMatrix={nodes.pPlane338_Paramount_0.instanceMatrix} />
      <instancedMesh args={[nodes.pPlane60_Paramount_0.geometry, materials.Paramount, 5]} instanceMatrix={nodes.pPlane60_Paramount_0.instanceMatrix} />
      <instancedMesh args={[nodes.pPlane63_Paramount_0.geometry, materials.Paramount, 3]} instanceMatrix={nodes.pPlane63_Paramount_0.instanceMatrix} />
      <instancedMesh args={[nodes.pPlane66_Paramount_0.geometry, materials.Paramount, 3]} instanceMatrix={nodes.pPlane66_Paramount_0.instanceMatrix} />
      <instancedMesh args={[nodes.pCube101_Paramount_0.geometry, materials.Paramount, 2]} instanceMatrix={nodes.pCube101_Paramount_0.instanceMatrix} />
      <instancedMesh args={[nodes.pCube2_Paramount_0001.geometry, materials.Paramount, 2]} instanceMatrix={nodes.pCube2_Paramount_0001.instanceMatrix} />
      <instancedMesh args={[nodes.pCube6_Paramount_0001.geometry, materials.Paramount, 2]} instanceMatrix={nodes.pCube6_Paramount_0001.instanceMatrix} />
      <instancedMesh args={[nodes.pCube99_Paramount_0.geometry, materials.Paramount, 2]} instanceMatrix={nodes.pCube99_Paramount_0.instanceMatrix} />
      <instancedMesh args={[nodes.pCube2_Paramount_0.geometry, materials.Paramount, 2]} instanceMatrix={nodes.pCube2_Paramount_0.instanceMatrix} />
      <instancedMesh args={[nodes.pCube6_Paramount_0.geometry, materials.Paramount, 2]} instanceMatrix={nodes.pCube6_Paramount_0.instanceMatrix} />
      <instancedMesh args={[nodes.pCube7_Paramount_0.geometry, materials.Paramount, 2]} instanceMatrix={nodes.pCube7_Paramount_0.instanceMatrix} />
      <instancedMesh args={[nodes.pCube98_Paramount_0.geometry, materials.Paramount, 2]} instanceMatrix={nodes.pCube98_Paramount_0.instanceMatrix} />
      <instancedMesh args={[nodes.pCylinder1_Paramount_0.geometry, materials.Paramount, 2]} instanceMatrix={nodes.pCylinder1_Paramount_0.instanceMatrix} />
      <instancedMesh args={[nodes.polySurface1_Paramount_0.geometry, materials.Paramount, 2]} instanceMatrix={nodes.polySurface1_Paramount_0.instanceMatrix} />
      <instancedMesh args={[nodes.polySurface13_Paramount_0.geometry, materials.Paramount, 2]} instanceMatrix={nodes.polySurface13_Paramount_0.instanceMatrix} />
      <instancedMesh args={[nodes.polySurface14_Paramount_0.geometry, materials.Paramount, 2]} instanceMatrix={nodes.polySurface14_Paramount_0.instanceMatrix} />
      <instancedMesh args={[nodes.polySurface16_Paramount_0.geometry, materials.Paramount, 2]} instanceMatrix={nodes.polySurface16_Paramount_0.instanceMatrix} />
      <instancedMesh args={[nodes.pasted__loftedSurface3_Pawnshop1GLOW_0.geometry, materials.Pawnshop1GLOW, 3]} instanceMatrix={nodes.pasted__loftedSurface3_Pawnshop1GLOW_0.instanceMatrix} />
      <instancedMesh args={[nodes.pasted__loftedSurface3_Pawnshop_0.geometry, materials.Pawnshop, 3]} instanceMatrix={nodes.pasted__loftedSurface3_Pawnshop_0.instanceMatrix} />
      <instancedMesh args={[nodes.pasted__pCube80_Pawnshop_0.geometry, materials.Pawnshop, 3]} instanceMatrix={nodes.pasted__pCube80_Pawnshop_0.instanceMatrix} />
      <instancedMesh args={[nodes.pasted__pCube81_Pawnshop_0.geometry, materials.Pawnshop, 3]} instanceMatrix={nodes.pasted__pCube81_Pawnshop_0.instanceMatrix} />
      <instancedMesh args={[nodes.pasted__polySurface804_Pawnshop_0.geometry, materials.Pawnshop, 3]} instanceMatrix={nodes.pasted__polySurface804_Pawnshop_0.instanceMatrix} />
      <instancedMesh args={[nodes.pasted__pCube88_Pawnshop_0.geometry, materials.Pawnshop, 3]} instanceMatrix={nodes.pasted__pCube88_Pawnshop_0.instanceMatrix} />
      <instancedMesh args={[nodes.pasted__BD_ConcreteBlock1_RoadsGround_0004.geometry, materials.RoadsGround, 8]} instanceMatrix={nodes.pasted__BD_ConcreteBlock1_RoadsGround_0004.instanceMatrix} />
      <instancedMesh args={[nodes.pasted__polySurface805_Pawnshop_0001.geometry, materials.Pawnshop, 2]} instanceMatrix={nodes.pasted__polySurface805_Pawnshop_0001.instanceMatrix} />
      <instancedMesh args={[nodes.pasted__polySurface806_Pawnshop_0001.geometry, materials.Pawnshop, 2]} instanceMatrix={nodes.pasted__polySurface806_Pawnshop_0001.instanceMatrix} />
      <instancedMesh args={[nodes.pasted__pCube84_Pawnshop_0001.geometry, materials.Pawnshop, 2]} instanceMatrix={nodes.pasted__pCube84_Pawnshop_0001.instanceMatrix} />
      <instancedMesh args={[nodes.pasted__pCube85_Pawnshop_0001.geometry, materials.Pawnshop, 2]} instanceMatrix={nodes.pasted__pCube85_Pawnshop_0001.instanceMatrix} />
      <instancedMesh args={[nodes.pasted__pCube88_Pawnshop1GLOW_0001.geometry, materials.Pawnshop1GLOW, 2]} instanceMatrix={nodes.pasted__pCube88_Pawnshop1GLOW_0001.instanceMatrix} />
      <instancedMesh args={[nodes.pasted__pCube89_Pawnshop_0001.geometry, materials.Pawnshop, 2]} instanceMatrix={nodes.pasted__pCube89_Pawnshop_0001.instanceMatrix} />
      <instancedMesh args={[nodes.pasted__pCube90_Pawnshop_0001.geometry, materials.Pawnshop, 2]} instanceMatrix={nodes.pasted__pCube90_Pawnshop_0001.instanceMatrix} />
      <instancedMesh args={[nodes.pasted__pCube91_Pawnshop_0001.geometry, materials.Pawnshop, 2]} instanceMatrix={nodes.pasted__pCube91_Pawnshop_0001.instanceMatrix} />
      <instancedMesh args={[nodes.pasted__pCube92_Pawnshop_0001.geometry, materials.Pawnshop, 2]} instanceMatrix={nodes.pasted__pCube92_Pawnshop_0001.instanceMatrix} />
      <instancedMesh args={[nodes.pasted__polySurface807_Pawnshop_0001.geometry, materials.Pawnshop, 2]} instanceMatrix={nodes.pasted__polySurface807_Pawnshop_0001.instanceMatrix} />
      <instancedMesh args={[nodes.pasted__pCube18_LMProjects_0.geometry, materials.LMProjects, 2]} instanceMatrix={nodes.pasted__pCube18_LMProjects_0.instanceMatrix} />
      <instancedMesh args={[nodes.pasted__pCube56_LMProjects_0.geometry, materials.LMProjects, 7]} instanceMatrix={nodes.pasted__pCube56_LMProjects_0.instanceMatrix} />
      <instancedMesh args={[nodes.polySurface750_WhiteGlow1_0.geometry, materials.PaletteMaterial001, 19]} instanceMatrix={nodes.polySurface750_WhiteGlow1_0.instanceMatrix} />
      <instancedMesh args={[nodes.polySurface839_WhiteGlow1_0.geometry, materials.PaletteMaterial001, 6]} instanceMatrix={nodes.polySurface839_WhiteGlow1_0.instanceMatrix} />
      <instancedMesh args={[nodes.polySurface791_CityProps_0001.geometry, materials.CityProps, 25]} instanceMatrix={nodes.polySurface791_CityProps_0001.instanceMatrix} />
      <instancedMesh args={[nodes.polySurface264_CityProps_0002.geometry, materials.CityProps, 25]} instanceMatrix={nodes.polySurface264_CityProps_0002.instanceMatrix} />
      <instancedMesh args={[nodes.polySurface262_CityProps_0006.geometry, materials.CityProps, 25]} instanceMatrix={nodes.polySurface262_CityProps_0006.instanceMatrix} />
      <instancedMesh args={[nodes.polySurface739_CityProps_0004.geometry, materials.CityProps, 19]} instanceMatrix={nodes.polySurface739_CityProps_0004.instanceMatrix} />
      <instancedMesh args={[nodes.polySurface262_CityProps_0008.geometry, materials.CityProps, 25]} instanceMatrix={nodes.polySurface262_CityProps_0008.instanceMatrix} />
      <instancedMesh args={[nodes.polySurface262_CityProps_0007.geometry, materials.CityProps, 25]} instanceMatrix={nodes.polySurface262_CityProps_0007.instanceMatrix} />
      <instancedMesh args={[nodes.polySurface264_CityProps_0003.geometry, materials.CityProps, 25]} instanceMatrix={nodes.polySurface264_CityProps_0003.instanceMatrix} />
      <instancedMesh args={[nodes.polySurface262_CityProps_0009.geometry, materials.CityProps, 25]} instanceMatrix={nodes.polySurface262_CityProps_0009.instanceMatrix} />
      <instancedMesh args={[nodes.polySurface739_CityProps_0006.geometry, materials.CityProps, 12]} instanceMatrix={nodes.polySurface739_CityProps_0006.instanceMatrix} />
      <instancedMesh args={[nodes.polySurface262_CityProps_0011.geometry, materials.CityProps, 25]} instanceMatrix={nodes.polySurface262_CityProps_0011.instanceMatrix} />
      <instancedMesh args={[nodes.polySurface739_GreenGlow_0001.geometry, materials.PaletteMaterial001, 12]} instanceMatrix={nodes.polySurface739_GreenGlow_0001.instanceMatrix} />
      <instancedMesh args={[nodes.polySurface262_CityProps_0010.geometry, materials.CityProps, 25]} instanceMatrix={nodes.polySurface262_CityProps_0010.instanceMatrix} />
      <instancedMesh args={[nodes.polySurface739_CityProps_0007.geometry, materials.CityProps, 25]} instanceMatrix={nodes.polySurface739_CityProps_0007.instanceMatrix} />
      <instancedMesh args={[nodes.polySurface260_CityProps_0001.geometry, materials.CityProps, 25]} instanceMatrix={nodes.polySurface260_CityProps_0001.instanceMatrix} />
      <instancedMesh args={[nodes.polySurface261_CityProps_0001.geometry, materials.CityProps, 25]} instanceMatrix={nodes.polySurface261_CityProps_0001.instanceMatrix} />
      <instancedMesh args={[nodes.polySurface750_CityProps_0001.geometry, materials.CityProps, 25]} instanceMatrix={nodes.polySurface750_CityProps_0001.instanceMatrix} />
      <instancedMesh args={[nodes.polySurface259_CityProps_0.geometry, materials.CityProps, 24]} instanceMatrix={nodes.polySurface259_CityProps_0.instanceMatrix} />
      <instancedMesh args={[nodes.polySurface791_CityProps1GLOW_0.geometry, materials.CityProps1GLOW, 24]} instanceMatrix={nodes.polySurface791_CityProps1GLOW_0.instanceMatrix} />
      <instancedMesh args={[nodes.polySurface739_RedGLOW_0.geometry, materials.PaletteMaterial001, 6]} instanceMatrix={nodes.polySurface739_RedGLOW_0.instanceMatrix} />
      <instancedMesh args={[nodes.polySurface739_CityProps_0001.geometry, materials.CityProps, 13]} instanceMatrix={nodes.polySurface739_CityProps_0001.instanceMatrix} />
      <instancedMesh args={[nodes.polySurface752_CityProps_0.geometry, materials.CityProps, 24]} instanceMatrix={nodes.polySurface752_CityProps_0.instanceMatrix} />
      <instancedMesh args={[nodes.polySurface739_CityProps_0.geometry, materials.CityProps, 24]} instanceMatrix={nodes.polySurface739_CityProps_0.instanceMatrix} />
      <instancedMesh args={[nodes.polySurface739_RedGLOW_0001.geometry, materials.PaletteMaterial001, 13]} instanceMatrix={nodes.polySurface739_RedGLOW_0001.instanceMatrix} />
      <instancedMesh args={[nodes.polySurface739_CityProps_0003.geometry, materials.CityProps, 13]} instanceMatrix={nodes.polySurface739_CityProps_0003.instanceMatrix} />
      <instancedMesh args={[nodes.polySurface752_CityProps_0001.geometry, materials.CityProps, 24]} instanceMatrix={nodes.polySurface752_CityProps_0001.instanceMatrix} />
      <instancedMesh args={[nodes.polySurface739_GreenGlow_0002.geometry, materials.PaletteMaterial001, 11]} instanceMatrix={nodes.polySurface739_GreenGlow_0002.instanceMatrix} />
      <instancedMesh args={[nodes.polySurface750_CityProps_0004.geometry, materials.CityProps, 8]} instanceMatrix={nodes.polySurface750_CityProps_0004.instanceMatrix} />
      <instancedMesh args={[nodes.polySurface836_WhiteGlow_0.geometry, materials.PaletteMaterial001, 7]} instanceMatrix={nodes.polySurface836_WhiteGlow_0.instanceMatrix} />
    </group>
  )
}

useGLTF.preload('/CleanedCity1.glb')
